import {
    attribute,
    autoGeneratedHashKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table("posts")
export default class Post {
    @autoGeneratedHashKey()
    id: string;

    @attribute({defaultProvider: () => Date.now()})
    createdAt: number;

    @attribute()
    title: string;

    @attribute()
    userId: string;

    @attribute()
    content: string;

    @attribute()
    tags: string[];
}
